### ISSUE TITLE
Unrelated question about batch-transcode-video

### ISSUE THREAD

**Issue by JMoVS** [nwronski/mocha-annotated#1]
Hi @nwronski,

there is a large community around video_transcoding by don melton and you coded batch-transcode-video, but it has since been removed from Github.

I tried contacting you on Twitter but you don't seem to be active there. If you were to put the repo including license back up on Github, the community might be able to fork it and carry it forward. It seems to be a good base! I didn't find any forks on Github and npm lists the license as MIT but I can't find the appropriate license file anywhere. Is there any chance of getting the code resurrected so we can carry it forward?

**Comment by nwronski** [comment]
@JMoVS sorry about that, [it is public again now](https://github.com/nwronski/batch-transcode-video).

**Comment by JMoVS** [comment]
perfect, thanks a lot!
